[build]
  command = "go build -o ./public/auction-server"
  publish = "public"
  functions = "public"

[build.environment]
  GO_VERSION = "1.23"

[functions]
  external_node_modules = []
  node_bundler = "esbuild"

[dev]
  command = "go run main.go"
  port = 8080
  publish = "public"
